version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: id # postgres
      POSTGRES_PASSWORD: pw #
      POSTGRES_DB: db # postgres

volumes:
  postgres_data:
